################################################################################
# Plot RNAPII metagene profiles from precomputed RDS objects
################################################################################
#
# This script reads the final metagene RDS objects generated by
# 01_build_metagene_objects.R and creates the metagene profile plots used in the
# TFM figures.
#
# Signal matrices are not recalculated here. This script uses:
#   result$profile          Mean signal per bin and sample
#   result$sample_metadata  Sample labels, conditions and replicate information
#   result$settings         Profile type and analysis parameters
#
# Each plot is exported as:
#   1) A vector PDF for multipanel figure assembly.
#   2) A high-resolution PNG at 600 dpi.
#
################################################################################

# ==============================================================================
# 1. Packages
# ==============================================================================

suppressPackageStartupMessages({
  library(dplyr)
  library(ggplot2)
  library(cowplot)
})

# ==============================================================================
# 2. Input and output configuration
# ==============================================================================

rds_dir <- "../Script_Limpios/Metageneplot/R_objects"

outdir_plots <- "../Script_Limpios/Metageneplot/Metagene_plots"
outdir_tss <- file.path(outdir_plots, "TSS")
outdir_tss_tes <- file.path(outdir_plots, "TSS_TES")

dir.create(outdir_tss, recursive = TRUE, showWarnings = FALSE)
dir.create(outdir_tss_tes, recursive = TRUE, showWarnings = FALSE)

# Final metagene objects generated from protein-coding genes ≥3 kb.
tss_rds <- file.path(
  rds_dir,
  "metagene_TSS_protein_coding_min3kb.rds"
)

gene_body_rds <- file.path(
  rds_dir,
  "metagene_TSS_TES_protein_coding_min3kb.rds"
)

# Sample colours used consistently across the TFM figures.
chipseq_colors <- c(
  "DMSO Rep1" = "#007A3D",  # dark green
  "DMSO Rep2" = "#7AD151",  # light green
  "CPT Rep1"  = "#6A00A8",  # dark purple
  "CPT Rep2"  = "#C77CFF"   # light purple
)

# Output dimensions and resolution.
# PDF files are vector-based; dpi applies only to PNG files.
plot_width <- 9
plot_height <- 7
plot_dpi <- 1260

# ==============================================================================
# 3. Helper functions
# ==============================================================================

check_input_files <- function(files, label) {
  missing_files <- files[!file.exists(files)]
  
  if (length(missing_files) > 0) {
    stop(
      "Missing ", label, " file(s):\n",
      paste(missing_files, collapse = "\n"),
      call. = FALSE
    )
  }
}

make_default_sample_metadata <- function(sample_names) {
  # Fallback used only if an older object does not contain sample_metadata.
  data.frame(
    sample = sample_names,
    sample_label = gsub("_R([0-9]+)$", " Rep\\1", sample_names),
    stringsAsFactors = FALSE
  )
}

prepare_profile_for_plot <- function(metagene_object) {
  profile_df <- metagene_object$profile
  
  if (is.null(profile_df)) {
    stop("The RDS object does not contain result$profile.", call. = FALSE)
  }
  
  if (!all(c("sample", "x", "signal") %in% colnames(profile_df))) {
    stop(
      "result$profile must contain the columns: sample, x and signal.",
      call. = FALSE
    )
  }
  
  sample_metadata <- metagene_object$sample_metadata
  
  if (is.null(sample_metadata)) {
    sample_metadata <- make_default_sample_metadata(
      unique(profile_df$sample)
    )
  }
  
  if (!"sample_label" %in% colnames(sample_metadata)) {
    sample_metadata$sample_label <- gsub(
      "_R([0-9]+)$",
      " Rep\\1",
      sample_metadata$sample
    )
  }
  
  profile_df <- profile_df %>%
    left_join(sample_metadata, by = "sample")
  
  if (any(is.na(profile_df$sample_label))) {
    missing_samples <- unique(
      profile_df$sample[is.na(profile_df$sample_label)]
    )
    
    stop(
      "Some samples in result$profile were not found in ",
      "result$sample_metadata: ",
      paste(missing_samples, collapse = ", "),
      call. = FALSE
    )
  }
  
  profile_df$sample_label <- factor(
    profile_df$sample_label,
    levels = sample_metadata$sample_label
  )
  
  profile_df
}


# Common theme in both plots
metagene_theme <- function(legend_position = "none") {
  theme_classic(base_size = 20, base_family = "sans") +
    theme(
      plot.title = element_blank(),
      axis.title = element_text(size = 26),
      axis.text = element_text(size = 22),
      legend.title = element_text(size = 18),
      legend.text = element_text(size = 16),
      legend.key.size = unit(0.5, "cm"),
      legend.position = legend_position,
      legend.direction = if (legend_position %in% c("right", "left")) {
        "vertical"
      } else {
        "horizontal"
      },
      plot.margin = margin(12, 22, 12, 12)
    )
}

# Metagene around TSS
plot_tss_metagene <- function(
    metagene_object,
    title,
    x_label = "Position relative to TSS (bp)",
    y_label = "Normalized RNAPII ChIP-seq signal",
    line_size = 1.4,
    legend_position = "none"
) {
  profile_df <- prepare_profile_for_plot(metagene_object)
  
  legend_guide <- if (legend_position %in% c("right", "left")) {
    guide_legend(ncol = 1)
  } else if (legend_position %in% c("bottom", "top")) {
    guide_legend(nrow = 1)
  } else {
    guide_legend()
  }
  
  ggplot(
    profile_df,
    aes(
      x = x,
      y = signal,
      color = sample_label
    )
  ) +
    geom_line(linewidth = line_size) +
    geom_vline(
      xintercept = 0,
      linetype = "dashed",
      linewidth = 0.7
    ) +
    scale_color_manual(
      values = chipseq_colors,
      breaks = names(chipseq_colors),
      drop = FALSE,
      guide = legend_guide
    ) +
    labs(
      x = x_label,
      y = y_label,
      color = NULL
    ) +
    metagene_theme(legend_position = legend_position)
}

# Metagene TSS - TES
plot_gene_body_metagene <- function(
    metagene_object,
    title,
    x_label = "Scaled gene body position",
    y_label = "Normalized RNAPII ChIP-seq signal",
    line_size = 1.4,
    legend_position = "none"
) {
  profile_df <- prepare_profile_for_plot(metagene_object)
  
  legend_guide <- if (legend_position %in% c("right", "left")) {
    guide_legend(ncol = 1)
  } else if (legend_position %in% c("bottom", "top")) {
    guide_legend(nrow = 1)
  } else {
    guide_legend()
  }
  
  ggplot(
    profile_df,
    aes(
      x = x,
      y = signal,
      color = sample_label
    )
  ) +
    geom_line(linewidth = line_size) +
    scale_x_continuous(
      breaks = c(0, 1),
      labels = c("TSS", "TES"),
      expand = expansion(mult = c(0, 0))
    ) +
    scale_color_manual(
      values = chipseq_colors,
      breaks = names(chipseq_colors),
      drop = FALSE,
      guide = legend_guide
    ) +
    labs(
      x = x_label,
      y = y_label,
      color = NULL
    ) +
    metagene_theme(legend_position = legend_position)
}

save_metagene_plot <- function(plot, output_base) {
  pdf_file <- paste0(output_base, ".pdf")
  png_file <- paste0(output_base, ".png")
  
  # Vector file for figure assembly and lossless resizing.
  ggsave(
    filename = pdf_file,
    plot = plot,
    device = "pdf",
    width = plot_width,
    height = plot_height,
    units = "in",
    bg = "white",
    limitsize = FALSE
  )
  
  # High-resolution copy.
  ggsave(
    filename = png_file,
    plot = plot,
    device = "png",
    width = plot_width,
    height = plot_height,
    units = "in",
    dpi = plot_dpi,
    bg = "white",
    limitsize = FALSE
  )
  
  message("  Saved vector plot: ", pdf_file)
  message("  Saved high-resolution plot: ", png_file)
}

save_plot_legend <- function(plot, output_base) {
  pdf_file <- paste0(output_base, ".pdf")
  png_file <- paste0(output_base, ".png")
  
  legend_only <- cowplot::get_legend(plot)
  legend_plot <- cowplot::ggdraw(legend_only)
  
  ggsave(
    filename = pdf_file,
    plot = legend_plot,
    device = "pdf",
    width = 2.4,
    height = 2.8,
    units = "in",
    bg = "white",
    limitsize = FALSE
  )
  
  ggsave(
    filename = png_file,
    plot = legend_plot,
    device = "png",
    width = 2.4,
    height = 2.8,
    units = "in",
    dpi = plot_dpi,
    bg = "white",
    limitsize = FALSE
  )
  
  message("  Saved legend PDF: ", pdf_file)
  message("  Saved legend PNG: ", png_file)
}

# ==============================================================================
# 4. Plot generation
# ==============================================================================

check_input_files(
  c(tss_rds, gene_body_rds),
  label = "metagene RDS"
)

message("============================================================================")
message("Plotting final RNAPII metagene profiles")

# ------------------------------------------------------------------------------
# TSS ±3 kb profile
# ------------------------------------------------------------------------------

tss_object <- readRDS(tss_rds)

p_tss_no_legend <- plot_tss_metagene(
  metagene_object = tss_object,
  title = "RNAPII occupancy around the TSS",
  legend_position = "none"
)

save_metagene_plot(
  plot = p_tss_no_legend,
  output_base = file.path(
    outdir_tss,
    "metagene_TSS_protein_coding_min3kb_NO_LEGEND_FINAL"
  )
)

# ------------------------------------------------------------------------------
# Scaled TSS–TES gene-body profile
# ------------------------------------------------------------------------------

gene_body_object <- readRDS(gene_body_rds)

p_gene_body_no_legend <- plot_gene_body_metagene(
  metagene_object = gene_body_object,
  title = "RNAPII occupancy across gene bodies",
  legend_position = "none"
)

save_metagene_plot(
  plot = p_gene_body_no_legend,
  output_base = file.path(
    outdir_tss_tes,
    "metagene_TSS_TES_protein_coding_min3kb_NO_LEGEND_FINAL"
  )
)

# ------------------------------------------------------------------------------
# Common vertical legend
# ------------------------------------------------------------------------------

p_common_legend_source <- plot_tss_metagene(
  metagene_object = tss_object,
  title = "RNAPII occupancy around the TSS",
  legend_position = "right"
)

save_plot_legend(
  plot = p_common_legend_source,
  output_base = file.path(
    outdir_plots,
    "metagene_common_legend_VERTICAL_FINAL"
  )
)

message("============================================================================")
message("Done. Metagene profile plots saved in: ", outdir_plots)