# ==============================================================================
# Differential RNAPII occupancy analysis with DESeq2
# ==============================================================================
# This script identifies changes in RNAPII ChIP-seq occupancy between CPT-treated
# and DMSO control samples using fragment counts from internal gene-body regions.
#
# Inputs:
#   - RNAPII ChIP-seq count matrix generated by featureCounts
#   - spike-in-derived DESeq2 size factors
#
# Main analysis decisions:
#   - genes with fewer than 100 total fragments across all samples are removed
#   - spike-in-derived size factors are assigned before running DESeq2
#   - the reported contrast is CPT versus DMSO
#   - differential occupancy is defined using:
#       adjusted p-value <= 0.05
#       absolute log2 fold change > 1
#
# Positive log2 fold changes indicate increased RNAPII occupancy in CPT.
# ==============================================================================

library(DESeq2)
library(dplyr)
library(ggplot2)
library(tibble)
library(cowplot)

# ------------------------------------------------------------------------------
# 1. Input and output paths
# ------------------------------------------------------------------------------

count_file <- file.path(
  "../Script_Limpios",
  "Count_Matrix_ChIPseq",
  "RNAPII_internal_gene_body",
  "RNAPII_ChIPseq_internal_gene_body_counts.tsv"
)

spike_factor_file <- file.path(
  "Data_final_CPT",
  "spikein_counts",
  "scale_factors.tsv"
)

output_dir <- file.path(
  "../Script_Limpios",
  "DESeq2_ChIPseq",
  "RNAPII_internal_gene_body"
)

table_dir <- file.path(output_dir, "tables")
plot_dir <- file.path(output_dir, "plots")

dir.create(table_dir, recursive = TRUE, showWarnings = FALSE)
dir.create(plot_dir, recursive = TRUE, showWarnings = FALSE)

# ------------------------------------------------------------------------------
# 2. Validate and import the count matrix
# ------------------------------------------------------------------------------

if (!file.exists(count_file)) {
  stop("The RNAPII ChIP-seq count matrix was not found: ", count_file,
       call. = FALSE)
}

if (!file.exists(spike_factor_file)) {
  stop("The spike-in size-factor file was not found: ", spike_factor_file,
       call. = FALSE)
}

count_matrix <- read.delim(
  file = count_file,
  header = TRUE,
  sep = "\t",
  row.names = 1,
  check.names = FALSE
)

count_matrix <- as.matrix(count_matrix)
storage.mode(count_matrix) <- "numeric"

if (anyNA(count_matrix)) {
  stop("The count matrix contains missing or non-numeric values.",
       call. = FALSE)
}

if (any(count_matrix < 0)) {
  stop("The count matrix contains negative values.", call. = FALSE)
}

# featureCounts generates integer counts. Rounding is retained as a safeguard
# against accidental numeric conversion during file import.
count_matrix <- round(count_matrix)

expected_samples <- c("DMSO_R1", "CPT_R1", "DMSO_R2", "CPT_R2")

if (!setequal(colnames(count_matrix), expected_samples)) {
  stop(
    "The count-matrix columns do not match the expected samples: ",
    paste(expected_samples, collapse = ", "),
    call. = FALSE
  )
}

count_matrix <- count_matrix[, expected_samples, drop = FALSE]

# ------------------------------------------------------------------------------
# 3. Define sample metadata
# ------------------------------------------------------------------------------

sample_metadata <- data.frame(
  sample = expected_samples,
  treatment = factor(
    c("DMSO", "CPT", "DMSO", "CPT"),
    levels = c("DMSO", "CPT")
  ),
  replicate = factor(c("R1", "R1", "R2", "R2")),
  row.names = expected_samples
)

# ------------------------------------------------------------------------------
# 4. Import and match spike-in size factors
# ------------------------------------------------------------------------------

spike_factors <- read.delim(
  file = spike_factor_file,
  header = TRUE,
  sep = "\t",
  check.names = FALSE
)

required_spike_columns <- c("sample", "deseq2_size_factor")

if (!all(required_spike_columns %in% colnames(spike_factors))) {
  stop(
    "The spike-in file must contain the columns: ",
    paste(required_spike_columns, collapse = ", "),
    call. = FALSE
  )
}

spike_factors <- spike_factors %>%
  mutate(
    sample_clean = case_when(
      sample == "R1_RNAPII_AV_DM_S1"   ~ "DMSO_R1",
      sample == "R1_RNAPII_AV_CPT_S4"  ~ "CPT_R1",
      sample == "R2_RNAPII_AV_DM_S7"   ~ "DMSO_R2",
      sample == "R2_RNAPII_AV_CPT_S10" ~ "CPT_R2",
      TRUE ~ NA_character_
    )
  ) %>%
  filter(!is.na(sample_clean)) %>%
  arrange(match(sample_clean, expected_samples))

if (!identical(spike_factors$sample_clean, expected_samples)) {
  stop(
    "The spike-in samples could not be matched uniquely to the count matrix.",
    call. = FALSE
  )
}

if (
  anyNA(spike_factors$deseq2_size_factor) ||
  any(spike_factors$deseq2_size_factor <= 0)
) {
  stop("Spike-in DESeq2 size factors must be positive and non-missing.",
       call. = FALSE)
}

spike_size_factors <- spike_factors$deseq2_size_factor
names(spike_size_factors) <- spike_factors$sample_clean

# Save the exact size factors used in the analysis.
size_factor_table <- data.frame(
  sample = expected_samples,
  treatment = sample_metadata$treatment,
  replicate = sample_metadata$replicate,
  deseq2_size_factor = spike_size_factors[expected_samples]
)

write.table(
  size_factor_table,
  file = file.path(table_dir, "RNAPII_ChIPseq_spikein_size_factors_used.tsv"),
  sep = "\t",
  quote = FALSE,
  row.names = FALSE
)

# ------------------------------------------------------------------------------
# 5. Construct and filter the DESeq2 dataset
# ------------------------------------------------------------------------------

dds <- DESeqDataSetFromMatrix(
  countData = count_matrix,
  colData = sample_metadata,
  design = ~ treatment
)

genes_before_filtering <- nrow(dds)

keep <- rowSums(counts(dds)) >= 100
dds <- dds[keep, ]

genes_after_filtering <- nrow(dds)

if (genes_after_filtering == 0L) {
  stop("No genes remained after applying the total-count filter.",
       call. = FALSE)
}

filtering_summary <- data.frame(
  metric = c(
    "Genes before low-count filtering",
    "Genes retained with total counts >= 100",
    "Genes removed with total counts < 100"
  ),
  value = c(
    genes_before_filtering,
    genes_after_filtering,
    genes_before_filtering - genes_after_filtering
  )
)

write.table(
  filtering_summary,
  file = file.path(table_dir, "RNAPII_ChIPseq_filtering_summary.tsv"),
  sep = "\t",
  quote = FALSE,
  row.names = FALSE
)

# Assign the spike-in-derived size factors before fitting the model.
sizeFactors(dds) <- spike_size_factors[colnames(dds)]

dds <- DESeq(dds)

# ------------------------------------------------------------------------------
# 6. Extract differential occupancy results
# ------------------------------------------------------------------------------

res_CPT_vs_DMSO <- results(
  dds,
  contrast = c("treatment", "CPT", "DMSO"),
  alpha = 0.05
)

results_table <- as.data.frame(res_CPT_vs_DMSO) %>%
  rownames_to_column("gene_id") %>%
  mutate(
    significance = case_when(
      is.na(padj) ~ "padj_NA",
      padj <= 0.05 & log2FoldChange > 1 ~ "Up_in_CPT",
      padj <= 0.05 & log2FoldChange < -1 ~ "Down_in_CPT",
      TRUE ~ "Not_changed"
    )
  )

write.table(
  results_table,
  file = file.path(
    table_dir,
    "RNAPII_ChIPseq_DESeq2_CPT_vs_DMSO_all_genes.tsv"
  ),
  sep = "\t",
  quote = FALSE,
  row.names = FALSE
)

# Tables used directly in downstream integration analyses.
genes_up <- results_table %>%
  filter(significance == "Up_in_CPT")

genes_down <- results_table %>%
  filter(significance == "Down_in_CPT")

write.table(
  genes_up,
  file = file.path(
    table_dir,
    "RNAPII_ChIPseq_DESeq2_CPT_vs_DMSO_up.tsv"
  ),
  sep = "\t",
  quote = FALSE,
  row.names = FALSE
)

write.table(
  genes_down,
  file = file.path(
    table_dir,
    "RNAPII_ChIPseq_DESeq2_CPT_vs_DMSO_down.tsv"
  ),
  sep = "\t",
  quote = FALSE,
  row.names = FALSE
)

# ------------------------------------------------------------------------------
# 7. Export spike-in-normalized counts
# ------------------------------------------------------------------------------

normalized_counts <- counts(dds, normalized = TRUE) %>%
  as.data.frame() %>%
  rownames_to_column("gene_id")

write.table(
  normalized_counts,
  file = file.path(
    table_dir,
    "RNAPII_ChIPseq_spikein_normalized_counts.tsv"
  ),
  sep = "\t",
  quote = FALSE,
  row.names = FALSE
)

normalized_count_summary <- normalized_counts %>%
  mutate(
    DMSO_mean_normalized_count = rowMeans(
      dplyr::select(., DMSO_R1, DMSO_R2),
      na.rm = TRUE
    ),
    CPT_mean_normalized_count = rowMeans(
      dplyr::select(., CPT_R1, CPT_R2),
      na.rm = TRUE
    )
  ) %>%
  dplyr::select(
    gene_id,
    DMSO_mean_normalized_count,
    CPT_mean_normalized_count
  )

write.table(
  normalized_count_summary,
  file = file.path(
    table_dir,
    "RNAPII_ChIPseq_spikein_normalized_count_summary.tsv"
  ),
  sep = "\t",
  quote = FALSE,
  row.names = FALSE
)

# ------------------------------------------------------------------------------
# 8. Plot settings
# ------------------------------------------------------------------------------

occupancy_colours <- c(
  "Up_in_CPT" = "#C44E8C",
  "Down_in_CPT" = "#2C7FB8",
  "Not_changed" = "#D9D9D9",
  "padj_NA" = "#D9D9D9"
)

plot_breaks <- c("Up_in_CPT", "Down_in_CPT", "Not_changed")

plot_labels <- c(
  "Up_in_CPT" = "Increased in CPT",
  "Down_in_CPT" = "Decreased in CPT",
  "Not_changed" = "Not changed"
)

save_plot <- function(plot, filename, width, height) {
  ggsave(
    filename = file.path(plot_dir, paste0(filename, ".pdf")),
    plot = plot,
    width = width,
    height = height,
    device = cairo_pdf,
    bg = "white"
  )

  ggsave(
    filename = file.path(plot_dir, paste0(filename, ".png")),
    plot = plot,
    width = width,
    height = height,
    dpi = 1690,
    bg = "white"
  )
}

deseq2_theme <- function(show_legend = FALSE) {
  theme_classic(base_size = 22) +
    theme(
      plot.title = element_blank(),
      plot.subtitle = element_blank(),
      axis.title = element_text(size = 24),
      axis.text = element_text(size = 22, colour = "black"),
      axis.line = element_line(linewidth = 0.7),
      axis.ticks = element_line(linewidth = 0.7),
      axis.ticks.length = unit(0.25, "cm"),
      legend.position = if (show_legend) "right" else "none",
      legend.text = element_text(size = 20),
      legend.title = element_blank(),
      legend.key.size = unit(0.7, "cm"),
      plot.margin = margin(12, 16, 12, 12)
    )
}

save_common_deseq2_legend <- function(
    output_base,
    width = 3.2,
    height = 2.2
) {
  legend_source <- ggplot(
    data.frame(
      significance = factor(plot_breaks, levels = plot_breaks),
      x = seq_along(plot_breaks),
      y = 1
    ),
    aes(x = x, y = y, colour = significance)
  ) +
    geom_point(size = 6) +
    scale_colour_manual(
      values = occupancy_colours,
      breaks = plot_breaks,
      labels = plot_labels,
      drop = FALSE
    ) +
    labs(colour = NULL) +
    theme_void(base_size = 20) +
    theme(
      legend.position = "right",
      legend.text = element_text(size = 20),
      legend.key.size = unit(0.8, "cm")
    )
  
  legend_only <- cowplot::get_legend(legend_source)
  legend_plot <- cowplot::ggdraw(legend_only)
  
  ggsave(
    filename = paste0(output_base, ".pdf"),
    plot = legend_plot,
    width = width,
    height = height,
    device = cairo_pdf,
    bg = "white"
  )
  
  ggsave(
    filename = paste0(output_base, ".png"),
    plot = legend_plot,
    width = width,
    height = height,
    dpi = 1690,
    bg = "white"
  )
  
  message("  Saved common DESeq2 legend: ", output_base)
}

# ------------------------------------------------------------------------------
# 9. Volcano plot
# ------------------------------------------------------------------------------

valid_positive_padj <- results_table$padj[
  !is.na(results_table$padj) & results_table$padj > 0
]

if (length(valid_positive_padj) == 0L) {
  stop("No positive adjusted p-values are available for the volcano plot.",
       call. = FALSE)
}

minimum_positive_padj <- min(valid_positive_padj)

volcano_data <- results_table %>%
  filter(!is.na(padj), !is.na(log2FoldChange)) %>%
  mutate(
    padj_for_plot = pmax(padj, minimum_positive_padj),
    negative_log10_padj = -log10(padj_for_plot)
  )

volcano_plot <- ggplot(
  volcano_data,
  aes(
    x = log2FoldChange,
    y = negative_log10_padj,
    colour = significance
  )
) +
  geom_point(alpha = 0.7, size = 2.0) +
  geom_vline(
    xintercept = c(-1, 1),
    linetype = "dashed",
    linewidth = 0.4
  ) +
  geom_hline(
    yintercept = -log10(0.05),
    linetype = "dashed",
    linewidth = 0.4
  ) +
  scale_colour_manual(
    values = occupancy_colours,
    breaks = plot_breaks,
    labels = plot_labels,
    drop = FALSE
  ) +
  labs(
    x = "log2 fold change",
    y = expression(-log[10]("adjusted p-value")),
    colour = NULL
  ) +
  deseq2_theme(show_legend = FALSE)

save_plot(
  volcano_plot,
  "RNAPII_ChIPseq_DESeq2_CPT_vs_DMSO_volcano",
  width = 7,
  height = 5
)

# ------------------------------------------------------------------------------
# 10. MA plot
# ------------------------------------------------------------------------------

ma_data <- results_table %>%
  filter(
    !is.na(baseMean),
    baseMean > 0,
    !is.na(log2FoldChange)
  )

ma_plot <- ggplot(
  ma_data,
  aes(
    x = baseMean,
    y = log2FoldChange,
    colour = significance
  )
) +
  geom_point(alpha = 0.7, size = 2.0) +
  scale_x_log10() +
  geom_hline(yintercept = 0, linewidth = 0.4) +
  geom_hline(
    yintercept = c(-1, 1),
    linetype = "dashed",
    linewidth = 0.4
  ) +
  scale_colour_manual(
    values = occupancy_colours,
    breaks = plot_breaks,
    labels = plot_labels,
    drop = FALSE
  ) +
  labs(
    x = "Mean spike-in-normalized count",
    y = "log2 fold change",
    colour = NULL
  ) +
  deseq2_theme(show_legend = FALSE)

save_plot(
  ma_plot,
  "RNAPII_ChIPseq_DESeq2_CPT_vs_DMSO_MA",
  width = 7,
  height = 5
)

# ------------------------------------------------------------------------------
# 11. DESeq2 category plot
# ------------------------------------------------------------------------------

category_data <- results_table %>%
  dplyr::filter(significance %in% plot_breaks) %>%
  dplyr::count(significance) %>%
  dplyr::mutate(
    percentage = 100 * n / sum(n),
    label = paste0(
      n,
      "\n",
      round(percentage, 1),
      "%"
    ),
    significance = factor(
      significance,
      levels = plot_breaks
    )
  )

category_plot <- ggplot(
  category_data,
  aes(x = "", y = n, fill = significance)
) +
  geom_col(width = 1, colour = "white", linewidth = 1.0) +
  coord_polar(theta = "y") +
  geom_text(
    aes(label = label),
    position = position_stack(vjust = 0.5),
    size = 7.5,
    fontface = "bold",
    colour = "black",
    lineheight = 0.9
  ) +
  scale_fill_manual(
    values = occupancy_colours,
    breaks = plot_breaks,
    labels = plot_labels,
    drop = FALSE
  ) +
  labs(
    fill = NULL
  ) +
  theme_void(base_size = 22) +
  theme(
    plot.title = element_blank(),
    plot.subtitle = element_blank(),
    legend.position = "none",
    plot.margin = margin(8, 8, 8, 8)
  )

save_plot(
  category_plot,
  "RNAPII_ChIPseq_DESeq2_CPT_vs_DMSO_categories",
  width = 7,
  height = 5
)

# ------------------------------------------------------------------------------
# 12. DESeq2 common legend plot
# ------------------------------------------------------------------------------


save_common_deseq2_legend(
  output_base = file.path(
    plot_dir,
    "RNAPII_ChIPseq_DESeq2_CPT_vs_DMSO_common_legend"
  )
)
