# ==============================================================================
# Differential gene expression analysis with DESeq2
# ==============================================================================
# This script identifies RNA-seq expression changes between CPT-treated and DMSO
# control samples using exon-level gene counts generated by featureCounts.
#
# Main analysis decisions:
#   - genes with fewer than 100 total reads across all samples are removed
#   - DESeq2 estimates RNA-seq size factors from the count matrix
#   - the reported contrast is CPT versus DMSO
#   - differential expression is defined using:
#       adjusted p-value <= 0.05
#       absolute log2 fold change > 1
#
# Positive log2 fold changes indicate increased RNA abundance in CPT.
# ==============================================================================

library(DESeq2)
library(dplyr)
library(ggplot2)
library(tibble)

# ------------------------------------------------------------------------------
# 1. Input and output paths
# ------------------------------------------------------------------------------

count_file <- "../Datos_Bulk_RNAseq/counts/exon/featureCounts_exon.txt"

output_dir <- file.path(
  "../Script_Limpios",
  "DESeq2_RNAseq"
)

table_dir <- file.path(output_dir, "tables")
plot_dir <- file.path(output_dir, "plots")

dir.create(table_dir, recursive = TRUE, showWarnings = FALSE)
dir.create(plot_dir, recursive = TRUE, showWarnings = FALSE)

# ------------------------------------------------------------------------------
# 2. Validate and import the RNA-seq count matrix
# ------------------------------------------------------------------------------

if (!file.exists(count_file)) {
  stop(
    "The RNA-seq featureCounts file was not found: ",
    count_file,
    call. = FALSE
  )
}

featurecounts_table <- read.delim(
  file = count_file,
  header = TRUE,
  skip = 1,
  sep = "\t",
  row.names = 1,
  check.names = FALSE
)

# Standard featureCounts output contains five annotation columns after Geneid:
# Chr, Start, End, Strand and Length. All remaining columns contain sample counts.
if (ncol(featurecounts_table) <= 5L) {
  stop(
    "No RNA-seq sample count columns were detected in the featureCounts file.",
    call. = FALSE
  )
}

count_matrix <- featurecounts_table[, 6:ncol(featurecounts_table), drop = FALSE]

original_sample_names <- basename(colnames(count_matrix))
original_sample_names <- sub("\\.bam$", "", original_sample_names)

# Assign consistent internal sample names from the original pipeline names.
sample_name_map <- c(
  "DM_rep1" = "DMSO_R1",
  "DM_rep2" = "DMSO_R2",
  "DM_rep3" = "DMSO_R3",
  "DM_rep4" = "DMSO_R4",
  "CPT_rep1" = "CPT_R1",
  "CPT_rep2" = "CPT_R2",
  "CPT_rep3" = "CPT_R3",
  "CPT_rep4" = "CPT_R4"
)

sample_names <- unname(
  sample_name_map[original_sample_names]
)

if (anyNA(sample_names)) {
  stop(
    "Sample names could not be assigned for the following RNA-seq columns: ",
    paste(original_sample_names[is.na(sample_names)], collapse = ", "),
    call. = FALSE
  )
}

if (anyDuplicated(sample_names)) {
  stop(
    "More than one RNA-seq column was assigned to the same sample.",
    call. = FALSE
  )
}

expected_samples <- c(
  "DMSO_R1", "CPT_R1",
  "DMSO_R2", "CPT_R2",
  "DMSO_R3", "CPT_R3",
  "DMSO_R4", "CPT_R4"
)

if (!setequal(sample_names, expected_samples)) {
  stop(
    "The detected RNA-seq samples do not match the expected set: ",
    paste(expected_samples, collapse = ", "),
    call. = FALSE
  )
}

colnames(count_matrix) <- sample_names
count_matrix <- count_matrix[, expected_samples, drop = FALSE]
count_matrix <- as.matrix(count_matrix)
storage.mode(count_matrix) <- "numeric"

if (anyNA(count_matrix)) {
  stop(
    "The RNA-seq count matrix contains missing or non-numeric values.",
    call. = FALSE
  )
}

if (any(count_matrix < 0)) {
  stop(
    "The RNA-seq count matrix contains negative values.",
    call. = FALSE
  )
}

count_matrix <- round(count_matrix)

# ------------------------------------------------------------------------------
# 3. Define sample metadata
# ------------------------------------------------------------------------------

sample_metadata <- data.frame(
  sample = expected_samples,
  treatment = factor(
    c(
      "DMSO", "CPT",
      "DMSO", "CPT",
      "DMSO", "CPT",
      "DMSO", "CPT"
    ),
    levels = c("DMSO", "CPT")
  ),
  replicate = factor(
    c(
      "R1", "R1",
      "R2", "R2",
      "R3", "R3",
      "R4", "R4"
    )
  ),
  row.names = expected_samples
)

# ------------------------------------------------------------------------------
# 4. Construct and filter the DESeq2 dataset
# ------------------------------------------------------------------------------

dds <- DESeqDataSetFromMatrix(
  countData = count_matrix,
  colData = sample_metadata,
  design = ~ treatment
)

genes_before_filtering <- nrow(dds)

# Keep genes with at least 100 total reads across all eight RNA-seq samples.
keep <- rowSums(counts(dds)) >= 100
dds <- dds[keep, ]

genes_after_filtering <- nrow(dds)

if (genes_after_filtering == 0L) {
  stop(
    "No genes remained after applying the total-count filter.",
    call. = FALSE
  )
}

filtering_summary <- data.frame(
  metric = c(
    "Genes before low-count filtering",
    "Genes retained with total counts >= 100",
    "Genes removed with total counts < 100"
  ),
  value = c(
    genes_before_filtering,
    genes_after_filtering,
    genes_before_filtering - genes_after_filtering
  )
)

write.table(
  filtering_summary,
  file = file.path(table_dir, "RNAseq_filtering_summary.tsv"),
  sep = "\t",
  quote = FALSE,
  row.names = FALSE
)

# Unlike the ChIP-seq analysis, RNA-seq size factors are estimated directly by
# DESeq2 because no spike-in normalization is applied to this dataset.
dds <- DESeq(dds)

# Save the size factors estimated and used by DESeq2.
size_factor_table <- data.frame(
  sample = colnames(dds),
  treatment = sample_metadata[colnames(dds), "treatment"],
  replicate = sample_metadata[colnames(dds), "replicate"],
  deseq2_size_factor = sizeFactors(dds)
)

write.table(
  size_factor_table,
  file = file.path(table_dir, "RNAseq_DESeq2_size_factors_used.tsv"),
  sep = "\t",
  quote = FALSE,
  row.names = FALSE
)

# ------------------------------------------------------------------------------
# 5. Extract differential expression results
# ------------------------------------------------------------------------------

res_CPT_vs_DMSO <- results(
  dds,
  contrast = c("treatment", "CPT", "DMSO"),
  alpha = 0.05
)

results_table <- as.data.frame(res_CPT_vs_DMSO) %>%
  tibble::rownames_to_column("gene_id") %>%
  dplyr::mutate(
    significance = dplyr::case_when(
      is.na(padj) ~ "padj_NA",
      padj <= 0.05 & log2FoldChange > 1 ~ "Up_in_CPT",
      padj <= 0.05 & log2FoldChange < -1 ~ "Down_in_CPT",
      TRUE ~ "Not_changed"
    )
  )

write.table(
  results_table,
  file = file.path(
    table_dir,
    "RNAseq_DESeq2_CPT_vs_DMSO_all_genes.tsv"
  ),
  sep = "\t",
  quote = FALSE,
  row.names = FALSE
)

genes_up <- results_table %>%
  dplyr::filter(significance == "Up_in_CPT")

genes_down <- results_table %>%
  dplyr::filter(significance == "Down_in_CPT")

write.table(
  genes_up,
  file = file.path(
    table_dir,
    "RNAseq_DESeq2_CPT_vs_DMSO_up.tsv"
  ),
  sep = "\t",
  quote = FALSE,
  row.names = FALSE
)

write.table(
  genes_down,
  file = file.path(
    table_dir,
    "RNAseq_DESeq2_CPT_vs_DMSO_down.tsv"
  ),
  sep = "\t",
  quote = FALSE,
  row.names = FALSE
)

# ------------------------------------------------------------------------------
# 6. Export DESeq2-normalized RNA-seq counts
# ------------------------------------------------------------------------------

normalized_counts <- counts(dds, normalized = TRUE) %>%
  as.data.frame() %>%
  tibble::rownames_to_column("gene_id")

write.table(
  normalized_counts,
  file = file.path(
    table_dir,
    "RNAseq_DESeq2_normalized_counts.tsv"
  ),
  sep = "\t",
  quote = FALSE,
  row.names = FALSE
)

normalized_count_summary <- normalized_counts %>%
  dplyr::mutate(
    DMSO_mean_normalized_count = rowMeans(
      cbind(
        DMSO_R1,
        DMSO_R2,
        DMSO_R3,
        DMSO_R4
      ),
      na.rm = TRUE
    ),
    CPT_mean_normalized_count = rowMeans(
      cbind(
        CPT_R1,
        CPT_R2,
        CPT_R3,
        CPT_R4
      ),
      na.rm = TRUE
    )
  ) %>%
  dplyr::select(
    gene_id,
    DMSO_mean_normalized_count,
    CPT_mean_normalized_count
  )

write.table(
  normalized_count_summary,
  file = file.path(
    table_dir,
    "RNAseq_DESeq2_normalized_count_summary.tsv"
  ),
  sep = "\t",
  quote = FALSE,
  row.names = FALSE
)

# ------------------------------------------------------------------------------
# 7. Plot settings
# ------------------------------------------------------------------------------

expression_colours <- c(
  "Up_in_CPT" = "#C44E8C",
  "Down_in_CPT" = "#2C7FB8",
  "Not_changed" = "#D9D9D9",
  "padj_NA" = "#D9D9D9"
)

plot_breaks <- c("Up_in_CPT", "Down_in_CPT", "Not_changed")

plot_labels <- c(
  "Up_in_CPT" = "Up in CPT",
  "Down_in_CPT" = "Down in CPT",
  "Not_changed" = "Not changed"
)

save_plot <- function(plot, filename, width, height) {
  ggsave(
    filename = file.path(plot_dir, paste0(filename, ".pdf")),
    plot = plot,
    width = width,
    height = height,
    device = cairo_pdf,
    bg = "white"
  )

  ggsave(
    filename = file.path(plot_dir, paste0(filename, ".png")),
    plot = plot,
    width = width,
    height = height,
    dpi = 600,
    bg = "white"
  )
}

# ------------------------------------------------------------------------------
# 8. Volcano plot
# ------------------------------------------------------------------------------

valid_positive_padj <- results_table$padj[
  !is.na(results_table$padj) & results_table$padj > 0
]

if (length(valid_positive_padj) == 0L) {
  stop(
    "No positive adjusted p-values are available for the volcano plot.",
    call. = FALSE
  )
}

minimum_positive_padj <- min(valid_positive_padj)

volcano_data <- results_table %>%
  dplyr::filter(
    !is.na(padj),
    !is.na(log2FoldChange)
  ) %>%
  dplyr::mutate(
    padj_for_plot = pmax(padj, minimum_positive_padj),
    negative_log10_padj = -log10(padj_for_plot)
  )

volcano_plot <- ggplot(
  volcano_data,
  aes(
    x = log2FoldChange,
    y = negative_log10_padj,
    colour = significance
  )
) +
  geom_point(alpha = 0.7, size = 1.4) +
  geom_vline(
    xintercept = c(-1, 1),
    linetype = "dashed",
    linewidth = 0.4
  ) +
  geom_hline(
    yintercept = -log10(0.05),
    linetype = "dashed",
    linewidth = 0.4
  ) +
  scale_colour_manual(
    values = expression_colours,
    breaks = plot_breaks,
    labels = plot_labels,
    drop = FALSE
  ) +
  labs(
    title = "Differential gene expression",
    subtitle = "CPT versus DMSO",
    x = "log2 fold change",
    y = expression(-log[10]("adjusted p-value")),
    colour = NULL
  ) +
  theme_classic(base_size = 12) +
  theme(
    plot.title = element_text(face = "bold", hjust = 0.5),
    plot.subtitle = element_text(hjust = 0.5),
    axis.text = element_text(colour = "black"),
    legend.position = "right"
  )

save_plot(
  volcano_plot,
  "RNAseq_DESeq2_CPT_vs_DMSO_volcano",
  width = 7,
  height = 5
)

# ------------------------------------------------------------------------------
# 9. MA plot
# ------------------------------------------------------------------------------

ma_data <- results_table %>%
  dplyr::filter(
    !is.na(baseMean),
    baseMean > 0,
    !is.na(log2FoldChange)
  )

ma_plot <- ggplot(
  ma_data,
  aes(
    x = baseMean,
    y = log2FoldChange,
    colour = significance
  )
) +
  geom_point(alpha = 0.7, size = 1.4) +
  scale_x_log10() +
  geom_hline(yintercept = 0, linewidth = 0.4) +
  geom_hline(
    yintercept = c(-1, 1),
    linetype = "dashed",
    linewidth = 0.4
  ) +
  scale_colour_manual(
    values = expression_colours,
    breaks = plot_breaks,
    labels = plot_labels,
    drop = FALSE
  ) +
  labs(
    title = "Differential gene expression",
    subtitle = "CPT versus DMSO",
    x = "Mean DESeq2-normalized RNA-seq count",
    y = "log2 fold change",
    colour = NULL
  ) +
  theme_classic(base_size = 12) +
  theme(
    plot.title = element_text(face = "bold", hjust = 0.5),
    plot.subtitle = element_text(hjust = 0.5),
    axis.text = element_text(colour = "black"),
    legend.position = "right"
  )

save_plot(
  ma_plot,
  "RNAseq_DESeq2_CPT_vs_DMSO_MA",
  width = 7,
  height = 5
)

# ------------------------------------------------------------------------------
# 10. DESeq2 category plot
# ------------------------------------------------------------------------------

category_data <- results_table %>%
  dplyr::filter(significance %in% plot_breaks) %>%
  dplyr::group_by(significance) %>%
  dplyr::summarise(
    n = dplyr::n(),
    .groups = "drop"
  ) %>%
  dplyr::mutate(
    percentage = 100 * n / sum(n),
    label = paste0(n, "\n", round(percentage, 1), "%"),
    significance = factor(
      significance,
      levels = plot_breaks
    )
  )

category_plot <- ggplot(
  category_data,
  aes(x = "", y = n, fill = significance)
) +
  geom_col(width = 1, colour = "white", linewidth = 0.6) +
  coord_polar(theta = "y") +
  geom_text(
    aes(label = label),
    position = position_stack(vjust = 0.5),
    size = 3.8
  ) +
  scale_fill_manual(
    values = expression_colours,
    breaks = plot_breaks,
    labels = plot_labels,
    drop = FALSE
  ) +
  labs(
    title = "Differential gene expression categories",
    subtitle = "CPT versus DMSO",
    fill = NULL
  ) +
  theme_void(base_size = 12) +
  theme(
    plot.title = element_text(face = "bold", hjust = 0.5),
    plot.subtitle = element_text(hjust = 0.5),
    legend.position = "right"
  )

save_plot(
  category_plot,
  "RNAseq_DESeq2_CPT_vs_DMSO_categories",
  width = 6,
  height = 5
)
